const sb=window.lobiSupabase;const state={user:null,products:[],editingProduct:null,deleteProduct:null};const $=s=>document.querySelector(s);const el={loginScreen:$("#loginScreen"),loginForm:$("#loginForm"),loginEmail:$("#loginEmail"),loginPassword:$("#loginPassword"),loginButton:$("#loginButton"),loginMessage:$("#loginMessage"),adminApp:$("#adminApp"),adminEmail:$("#adminEmail"),logoutButton:$("#logoutButton"),sidebar:$("#sidebar"),mobileMenuButton:$("#mobileMenuButton"),statTotal:$("#statTotal"),statActive:$("#statActive"),statOut:$("#statOut"),newProductButton:$("#newProductButton"),productSearch:$("#productSearch"),categoryFilter:$("#categoryFilter"),statusFilter:$("#statusFilter"),sortFilter:$("#sortFilter"),clearProductFilters:$("#clearProductFilters"),refreshProductsButton:$("#refreshProductsButton"),resultsCount:$("#resultsCount"),loadingProducts:$("#loadingProducts"),emptyProducts:$("#emptyProducts"),productsTableWrap:$("#productsTableWrap"),productsTableBody:$("#productsTableBody"),productModal:$("#productModal"),productModalTitle:$("#productModalTitle"),closeProductModal:$("#closeProductModal"),cancelProductButton:$("#cancelProductButton"),productForm:$("#productForm"),productId:$("#productId"),productName:$("#productName"),productPrice:$("#productPrice"),productStock:$("#productStock"),productCategory:$("#productCategory"),productTag:$("#productTag"),productSizes:$("#productSizes"),productDescription:$("#productDescription"),productImage:$("#productImage"),currentImageUrl:$("#currentImageUrl"),currentImagePath:$("#currentImagePath"),productActive:$("#productActive"),imagePreviewWrap:$("#imagePreviewWrap"),imagePreview:$("#imagePreview"),productFormMessage:$("#productFormMessage"),saveProductButton:$("#saveProductButton"),deleteModal:$("#deleteModal"),cancelDeleteButton:$("#cancelDeleteButton"),confirmDeleteButton:$("#confirmDeleteButton"),toast:$("#toast"),productsView:$("#productsView"),pageView:$("#pageView"),productsNavButton:$("#productsNavButton"),pageNavButton:$("#pageNavButton"),mobileMenuButtonPage:$("#mobileMenuButtonPage")};
function formatMoney(v){return Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}function escapeHtml(v=""){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}function showToast(m,t="success"){el.toast.textContent=m;el.toast.className=`toast ${t==="error"?"error":""}`;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el.toast.classList.add("hidden"),3500)}function setLoading(b,on,n,l="AGUARDE..."){b.disabled=on;b.textContent=on?l:n}function showLogin(){el.loginScreen.classList.remove("hidden");el.adminApp.classList.add("hidden")}function showAdmin(){el.loginScreen.classList.add("hidden");el.adminApp.classList.remove("hidden");el.adminEmail.textContent=state.user?.email||"";let saved="products";try{saved=localStorage.getItem("lobiAdminView")||"products"}catch{}setTimeout(()=>{if(saved==="page")el.pageNavButton?.click();else switchAdminView("products")},0)}
async function isAdmin(uid){const{data,error}=await sb.rpc("is_admin",{p_uid:uid});if(error){console.error(error);return false}return data===true}
async function bootstrapAuth(){const{data,error}=await sb.auth.getSession();if(error||!data.session?.user){showLogin();return}if(!await isAdmin(data.session.user.id)){await sb.auth.signOut();showLogin();el.loginMessage.textContent="Esta conta não possui permissão de administrador.";return}state.user=data.session.user;showAdmin();await loadProducts()}
async function login(e){e.preventDefault();el.loginMessage.textContent="";setLoading(el.loginButton,true,"ENTRAR","ENTRANDO...");try{const{data,error}=await sb.auth.signInWithPassword({email:el.loginEmail.value.trim(),password:el.loginPassword.value});if(error)throw error;if(!await isAdmin(data.user.id)){await sb.auth.signOut();throw new Error("Esta conta não possui permissão de administrador.")}state.user=data.user;showAdmin();await loadProducts()}catch(error){console.error(error);el.loginMessage.textContent=error.message==="Invalid login credentials"?"E-mail ou senha incorretos.":error.message}finally{setLoading(el.loginButton,false,"ENTRAR")}}
async function logout(){await sb.auth.signOut();state.user=null;state.products=[];showLogin()}
async function loadProducts(){if(el.refreshProductsButton){el.refreshProductsButton.disabled=true;el.refreshProductsButton.textContent="↻ ATUALIZANDO..."}el.loadingProducts.classList.remove("hidden");el.emptyProducts.classList.add("hidden");el.productsTableWrap.classList.add("hidden");const{data,error}=await sb.from("products").select("*").order("created_at",{ascending:false});el.loadingProducts.classList.add("hidden");if(error){console.error(error);showToast("Não foi possível carregar os produtos.","error");if(el.refreshProductsButton){el.refreshProductsButton.disabled=false;el.refreshProductsButton.textContent="↻ ATUALIZAR"}return}state.products=(data||[]).filter(p=>!["__site_config__","__site_blocks__"].includes(p.category));refreshCategoryFilter();renderProducts();if(el.refreshProductsButton){el.refreshProductsButton.disabled=false;el.refreshProductsButton.textContent="↻ ATUALIZAR"}}
function refreshCategoryFilter(){const current=el.categoryFilter.value,cats=[...new Set(state.products.map(p=>p.category?.trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"pt-BR"));el.categoryFilter.innerHTML='<option value="">Todas as categorias</option>';cats.forEach(c=>{const o=document.createElement("option");o.value=c;o.textContent=c;el.categoryFilter.appendChild(o)});if(cats.includes(current))el.categoryFilter.value=current}
function filtered(){
  const s=el.productSearch.value.trim().toLowerCase(),c=el.categoryFilter.value,status=el.statusFilter?.value||"",sort=el.sortFilter?.value||"recent";
  const list=state.products.filter(p=>{
    const matchesText=!s||p.name?.toLowerCase().includes(s)||p.category?.toLowerCase().includes(s)||p.tag?.toLowerCase().includes(s);
    const matchesCategory=!c||p.category===c;
    const matchesStatus=!status||(status==="active"&&p.active)||(status==="inactive"&&!p.active)||(status==="out"&&Number(p.stock)<=0);
    return matchesText&&matchesCategory&&matchesStatus;
  });
  list.sort((a,b)=>{
    if(sort==="name")return String(a.name||"").localeCompare(String(b.name||""),"pt-BR");
    if(sort==="priceHigh")return Number(b.price||0)-Number(a.price||0);
    if(sort==="priceLow")return Number(a.price||0)-Number(b.price||0);
    if(sort==="stockLow")return Number(a.stock||0)-Number(b.stock||0);
    return new Date(b.created_at||0)-new Date(a.created_at||0);
  });
  return list;
}
function renderStats(){el.statTotal.textContent=state.products.length;el.statActive.textContent=state.products.filter(p=>p.active).length;el.statOut.textContent=state.products.filter(p=>Number(p.stock)<=0).length}
function renderProducts(){renderStats();const list=filtered();if(el.resultsCount)el.resultsCount.textContent=list.length+" "+(list.length===1?"produto":"produtos");document.querySelectorAll(".stat-action").forEach(card=>{const f=card.dataset.productFilter;card.classList.toggle("selected",(f==="all"&&!el.statusFilter?.value)||(f===el.statusFilter?.value))});el.productsTableBody.innerHTML="";if(!list.length){el.productsTableWrap.classList.add("hidden");el.emptyProducts.classList.remove("hidden");el.emptyProducts.textContent=state.products.length?"Nenhum produto corresponde aos filtros.":"Nenhum produto cadastrado ainda.";return}el.emptyProducts.classList.add("hidden");el.productsTableWrap.classList.remove("hidden");list.forEach(p=>{const tr=document.createElement("tr");tr.className="product-row";tr.tabIndex=0;tr.title="Clique para editar";const thumb=p.image_url?`<img class="product-thumb" src="${escapeHtml(p.image_url)}" alt="">`:'<div class="product-thumb-placeholder">▧</div>',sizes=Array.isArray(p.sizes)&&p.sizes.length?p.sizes.join(", "):"Sem tamanhos";tr.innerHTML=`<td><div class="product-cell">${thumb}<div><div class="product-name">${escapeHtml(p.name)}</div><div class="product-meta">${escapeHtml(p.tag||"SEM TAG")} · ${escapeHtml(sizes)}</div></div></div></td><td>${escapeHtml(p.category||"-")}</td><td>${formatMoney(p.price)}</td><td>${Number(p.stock||0)}</td><td><span class="status-pill ${p.active?"active":""}">${p.active?"Ativo":"Inativo"}</span></td><td><div class="table-actions"><button class="mini-btn edit-product" data-id="${p.id}">Editar</button><button class="mini-btn delete delete-product" data-id="${p.id}">Excluir</button></div></td>`;tr.addEventListener("click",e=>{if(e.target.closest("button"))return;openEditProduct(p.id)});tr.addEventListener("keydown",e=>{if((e.key==="Enter"||e.key===" ")&&!e.target.closest("button")){e.preventDefault();openEditProduct(p.id)}});el.productsTableBody.appendChild(tr)});document.querySelectorAll(".edit-product").forEach(b=>b.onclick=()=>openEditProduct(b.dataset.id));document.querySelectorAll(".delete-product").forEach(b=>b.onclick=()=>openDeleteModal(b.dataset.id))}
function clearProductFilters(){
  el.productSearch.value="";
  el.categoryFilter.value="";
  if(el.statusFilter)el.statusFilter.value="";
  if(el.sortFilter)el.sortFilter.value="recent";
  renderProducts();
  el.productSearch.focus();
}
function setStatFilter(filter){
  if(!el.statusFilter)return;
  el.statusFilter.value=filter==="all"?"":filter;
  renderProducts();
}
function clearForm(){el.productForm.reset();el.productId.value="";el.currentImageUrl.value="";el.currentImagePath.value="";el.productStock.value="0";el.productActive.checked=true;el.productFormMessage.textContent="";el.productImage.value="";el.imagePreview.src="";el.imagePreviewWrap.classList.add("hidden")}
function openNewProduct(){state.editingProduct=null;clearForm();el.productModalTitle.textContent="NOVO PRODUTO";el.productModal.classList.remove("hidden");document.body.style.overflow="hidden"}
function openEditProduct(id){const p=state.products.find(x=>x.id===id);if(!p)return;state.editingProduct=p;clearForm();el.productModalTitle.textContent="EDITAR PRODUTO";el.productId.value=p.id;el.productName.value=p.name||"";el.productPrice.value=p.price??"";el.productStock.value=p.stock??0;el.productCategory.value=p.category||"";el.productTag.value=p.tag||"";el.productSizes.value=Array.isArray(p.sizes)?p.sizes.join(", "):"";el.productDescription.value=p.description||"";el.productActive.checked=!!p.active;el.currentImageUrl.value=p.image_url||"";el.currentImagePath.value=p.image_path||"";if(p.image_url){el.imagePreview.src=p.image_url;el.imagePreviewWrap.classList.remove("hidden")}el.productModal.classList.remove("hidden");document.body.style.overflow="hidden"}
function closeProductModal(){el.productModal.classList.add("hidden");state.editingProduct=null;document.body.style.overflow=""}function parseSizes(v){return[...new Set(v.split(",").map(x=>x.trim()).filter(Boolean))]}function validateImage(f){if(!f)return;const allowed=["image/jpeg","image/png","image/webp"];if(!allowed.includes(f.type))throw new Error("Use uma imagem JPG, PNG ou WEBP.");if(f.size>5*1024*1024)throw new Error("A imagem deve ter no máximo 5 MB.")}function extFor(f){return{"image/jpeg":"jpg","image/png":"png","image/webp":"webp"}[f.type]||"jpg"}
async function uploadImage(f){validateImage(f);const path=`products/${crypto.randomUUID()}.${extFor(f)}`;const{error}=await sb.storage.from("product-images").upload(path,f,{cacheControl:"3600",upsert:false,contentType:f.type});if(error)throw error;const{data}=sb.storage.from("product-images").getPublicUrl(path);return{path,url:data.publicUrl}}async function removeImage(path){if(!path)return;const{error}=await sb.storage.from("product-images").remove([path]);if(error)console.warn(error)}
async function saveProduct(e){e.preventDefault();el.productFormMessage.textContent="";setLoading(el.saveProductButton,true,"SALVAR PRODUTO","SALVANDO...");let uploaded=null;try{const file=el.productImage.files[0];if(file)uploaded=await uploadImage(file);const payload={name:el.productName.value.trim(),price:Number(el.productPrice.value),category:el.productCategory.value.trim(),description:el.productDescription.value.trim()||null,sizes:parseSizes(el.productSizes.value),stock:Number(el.productStock.value||0),tag:el.productTag.value.trim()||null,active:el.productActive.checked,image_url:uploaded?.url||el.currentImageUrl.value||null,image_path:uploaded?.path||el.currentImagePath.value||null,updated_at:new Date().toISOString()};if(!payload.name)throw new Error("Informe o nome do produto.");if(!Number.isFinite(payload.price)||payload.price<0)throw new Error("Informe um preço válido.");if(!payload.category)throw new Error("Informe a categoria.");if(!Number.isInteger(payload.stock)||payload.stock<0)throw new Error("O estoque deve ser um número inteiro igual ou maior que zero.");const id=el.productId.value;if(id){const old=el.currentImagePath.value;const{error}=await sb.from("products").update(payload).eq("id",id);if(error)throw error;if(uploaded&&old&&old!==uploaded.path)await removeImage(old);showToast("Produto atualizado.")}else{if(!payload.image_url)throw new Error("Escolha uma imagem para o novo produto.");const{error}=await sb.from("products").insert(payload);if(error)throw error;showToast("Produto cadastrado.")}closeProductModal();await loadProducts()}catch(error){console.error(error);if(uploaded?.path)await removeImage(uploaded.path);el.productFormMessage.textContent=error.message||"Não foi possível salvar o produto."}finally{setLoading(el.saveProductButton,false,"SALVAR PRODUTO")}}
function preview(){const f=el.productImage.files[0];if(!f)return;try{validateImage(f)}catch(error){el.productFormMessage.textContent=error.message;el.productImage.value="";return}el.imagePreview.src=URL.createObjectURL(f);el.imagePreviewWrap.classList.remove("hidden")}
function openDeleteModal(id){const p=state.products.find(x=>x.id===id);if(!p)return;state.deleteProduct=p;el.deleteModal.classList.remove("hidden");document.body.style.overflow="hidden"}function closeDeleteModal(){state.deleteProduct=null;el.deleteModal.classList.add("hidden");document.body.style.overflow=""}
async function deleteProduct(){const p=state.deleteProduct;if(!p)return;setLoading(el.confirmDeleteButton,true,"EXCLUIR","EXCLUINDO...");try{const{error}=await sb.from("products").delete().eq("id",p.id);if(error)throw error;if(p.image_path)await removeImage(p.image_path);closeDeleteModal();showToast("Produto excluído.");await loadProducts()}catch(error){console.error(error);showToast(error.message||"Não foi possível excluir.","error")}finally{setLoading(el.confirmDeleteButton,false,"EXCLUIR")}}
el.loginForm.addEventListener("submit",login);el.logoutButton.addEventListener("click",logout);el.newProductButton.addEventListener("click",openNewProduct);el.closeProductModal.addEventListener("click",closeProductModal);el.cancelProductButton.addEventListener("click",closeProductModal);el.productForm.addEventListener("submit",saveProduct);el.productImage.addEventListener("change",preview);el.productSearch.addEventListener("input",renderProducts);el.categoryFilter.addEventListener("change",renderProducts);el.statusFilter?.addEventListener("change",renderProducts);el.sortFilter?.addEventListener("change",renderProducts);el.clearProductFilters?.addEventListener("click",clearProductFilters);el.refreshProductsButton?.addEventListener("click",loadProducts);document.querySelectorAll(".stat-action").forEach(card=>{card.addEventListener("click",()=>setStatFilter(card.dataset.productFilter));card.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setStatFilter(card.dataset.productFilter)}})});el.cancelDeleteButton.addEventListener("click",closeDeleteModal);el.confirmDeleteButton.addEventListener("click",deleteProduct);el.mobileMenuButton.addEventListener("click",()=>el.sidebar.classList.toggle("open"));el.productModal.addEventListener("click",e=>{if(e.target===el.productModal)closeProductModal()});el.deleteModal.addEventListener("click",e=>{if(e.target===el.deleteModal)closeDeleteModal()});document.addEventListener("keydown",e=>{
  const tag=(e.target?.tagName||"").toLowerCase(),typing=["input","textarea","select"].includes(tag)||e.target?.isContentEditable;
  if(e.key==="Escape"){
    if(!el.productModal.classList.contains("hidden"))closeProductModal();
    if(!el.deleteModal.classList.contains("hidden"))closeDeleteModal();
    el.sidebar.classList.remove("open");
    return;
  }
  if(e.altKey&&e.key==="1"){e.preventDefault();switchAdminView("products");return}
  if(e.altKey&&e.key==="2"){e.preventDefault();switchAdminView("page");el.pageNavButton?.click();return}
  if(typing||e.ctrlKey||e.metaKey||e.altKey)return;
  if(e.key==="/"){e.preventDefault();switchAdminView("products");el.productSearch.focus();return}
  if(e.key.toLowerCase()==="n"&&!el.productsView.classList.contains("hidden")){e.preventDefault();openNewProduct()}
});bootstrapAuth();

function switchAdminView(view){
  const page=view==="page";
  try{localStorage.setItem("lobiAdminView",page?"page":"products")}catch{}
  el.productsView?.classList.toggle("hidden",page);
  el.pageView?.classList.toggle("hidden",!page);
  el.productsNavButton?.classList.toggle("active",!page);
  el.pageNavButton?.classList.toggle("active",page);
  el.sidebar?.classList.remove("open");
}
el.productsNavButton?.addEventListener("click",()=>switchAdminView("products"));
el.pageNavButton?.addEventListener("click",()=>switchAdminView("page"));
el.mobileMenuButtonPage?.addEventListener("click",()=>el.sidebar.classList.toggle("open"));
